# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: postgresql
  encoding: unicode
  database: d6g0b6v14dv82o
  pool: 5
  username: nuzlzqqwczdtqi
  password: GFqdG73sdWD_0LTzISXKbvp_-o
  host: ec2-107-22-166-233.compute-1.amazonaws.com
  port: 5432
